-- CREACION BD
create user turismo_real identified by portafolio;
grant connect, resource to turismo_real;

-- SELECT
SELECT * FROM TIPO_USUARIO;
SELECT * FROM PAIS;
SELECT * FROM GENERO;
SELECT * FROM CONDUCTOR;
SELECT * FROM REGION;
SELECT * FROM COMUNA;
SELECT * FROM IMAGEN;
SELECT * FROM TIPO_DEPARTAMENTO;
SELECT * FROM TIPO_MANTENCION;
SELECT * FROM ESTADO_MANTENCION;
SELECT * FROM INSTALACION;
SELECT * FROM ESTADO_RESERVA;
SELECT * FROM ESTADO_DEPTO;
SELECT * FROM TIPO_PAGO;
SELECT * FROM ASISTENTE;
SELECT * FROM TIPO_SERVICIO;
SELECT * FROM SERVICIO;
SELECT * FROM TIPO_GASTO;
SELECT * FROM INVENTARIO;
SELECT * FROM DIRECCION;
SELECT * FROM USUARIO;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM RESERVA;
SELECT * FROM SERVICIO_RESERVA;
SELECT * FROM ASISTENTE_RESERVA;
SELECT * FROM MANTENCION;
SELECT * FROM PAGO;
SELECT * FROM INSTALACION_DEPARTAMENTO;
SELECT * FROM GASTO;